camera0: 0
camera1: 15
frame_width: 640
frame_height: 480
mono_calibration_frames: 20
stereo_calibration_frames: 10
view_resize: 2
checkerboard_box_size_scale : 3.19
checkerboard_rows: 9
checkerboard_columns: 8
cooldown: 100
